# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bind.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bind.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbind.proto\x12\x04\x62ind\"$\n\x0eProblemRequest\x12\x12\n\ntitle_slug\x18\x01 \x01(\t\"%\n\x10ProblemStatement\x12\x11\n\tstatement\x18\x01 \x01(\t2R\n\x10StatementService\x12>\n\x0cGetStatement\x12\x14.bind.ProblemRequest\x1a\x16.bind.ProblemStatement\"\x00\x42\x0cZ\n./bindingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bind_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./bindings'
  _globals['_PROBLEMREQUEST']._serialized_start=20
  _globals['_PROBLEMREQUEST']._serialized_end=56
  _globals['_PROBLEMSTATEMENT']._serialized_start=58
  _globals['_PROBLEMSTATEMENT']._serialized_end=95
  _globals['_STATEMENTSERVICE']._serialized_start=97
  _globals['_STATEMENTSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
